stages:
  - mavenbuild
  - maventest

maven-build:
  stage: mavenbuild
  tags:
    - martin_tag      # <-- change to your runner's tag
  script:
    - cd Backend        # change 'Backend' to where you have the pom.xml (do not add / in the beginning)
    - mvn package
  only:
    refs:
      - Martin_CICD
    changes:
      - Backend/**/*


maven-test:
  stage: maventest
  tags:
    - martin_tag     # <-- change to your runner's tag
  script:
    - cd Backend       # change 'Backend' to where you have the pom.xml (do not add / in the beginning)
    - mvn test
  only:
    refs:
      - Martin_CICD
    changes:
      - Backend/**/*
